### ISSUE TITLE
Tabs are hidden when they only consist of groups of properties

### ISSUE THREAD

**Issue by davidstroem** [Matthew-Wise/feature-flagging-umbraco#11]
If you create a tab with groups of properties, the tab is hidden by this package. There should be a check for !Tabs.Properties.Any() before looping through properties and checking features.

![image](https://github.com/Matthew-Wise/feature-flagging-umbraco/assets/80402985/59bb9630-804e-46d8-b601-33801b2de687)

CMS: 12.2.0

Our.FeatureFlags: Latest version

**Comment by Matthew-Wise** [comment]
Thanks @davidstroem, I will need to take a look at this, as I need to work out if its possible to hide the tab if the group has no properties.

**Comment by Matthew-Wise** [comment]
Hi @davidstroem 

A little more delayed than I wanted but version 2.1.0 is now out with a fix for this - https://www.nuget.org/packages/Our.FeatureFlags/2.1.0 along with updated dependencies.
